# Generated by Django 2.2 on 2019-04-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child3',
            name='child2',
        ),
        migrations.DeleteModel(
            name='Child2',
        ),
        migrations.DeleteModel(
            name='Child3',
        ),
    ]
